/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-primary": "#ffffff",
              "surface-container-high": "#f0e6e0",
              "tertiary-fixed": "#ffdad6",
              "inverse-primary": "#a1d494",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed": "#410003",
              "surface-dim": "#e2d8d2",
              "primary": "#154212",
              "tertiary-fixed-dim": "#ffb4ac",
              "on-surface": "#1f1b17",
              "tertiary": "#79000a",
              "secondary": "#914d00",
              "on-error-container": "#93000a",
              "on-primary-fixed": "#002201",
              "on-background": "#1f1b17",
              "on-secondary-container": "#663400",
              "surface-container-highest": "#eae1db",
              "inverse-surface": "#342f2c",
              "secondary-fixed": "#ffdcc3",
              "on-primary-fixed-variant": "#23501e",
              "surface": "#fff8f5",
              "on-tertiary-fixed-variant": "#8e1115",
              "on-surface-variant": "#42493e",
              "on-tertiary-container": "#ffaea6",
              "background": "#fff8f5",
              "inverse-on-surface": "#f9efe9",
              "on-surface-dark": "#1f1b17",
              "outline-earth": "#72796e",
              "surface-container-low": "#fcf2ec",
              "secondary-fixed-dim": "#ffb77e",
              "surface-warm": "#fff8f5",
              "outline-variant": "#c2c9bb",
              "secondary-container": "#fe932c",
              "on-error": "#ffffff",
              "success-green": "#154212",
              "surface-bright": "#fff8f5",
              "outline": "#72796e",
              "tertiary-container": "#9c1d1d",
              "primary-fixed": "#bcf0ae",
              "surface-container": "#f6ece6",
              "primary-fixed-dim": "#a1d494",
              "error-container": "#ffdad6",
              "surface-tint": "#3b6934",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed": "#2f1500",
              "error": "#ba1a1a",
              "on-primary-container": "#9dd090",
              "primary-container": "#2d5a27",
              "surface-variant": "#eae1db",
              "on-secondary-fixed-variant": "#6e3900",
              "on-secondary": "#ffffff"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "desktop-margin": "auto",
              "mobile-margin": "1.25rem",
              "gutter": "1rem",
              "stack-lg": "1.5rem",
              "touch-target": "3rem",
              "max-width-desktop": "1200px",
              "stack-sm": "0.5rem",
              "stack-md": "1rem",
              "tablet-margin": "2rem"
          },
          "fontFamily": {
              "body-lg": ["Be Vietnam Pro"],
              "display-lg": ["Be Vietnam Pro"],
              "headline-md": ["Be Vietnam Pro"],
              "body-md": ["Be Vietnam Pro"],
              "headline-lg": ["Be Vietnam Pro"],
              "label-md": ["Be Vietnam Pro"],
              "headline-lg-mobile": ["Be Vietnam Pro"],
              "label-lg": ["Be Vietnam Pro"]
          },
          "fontSize": {
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
              "headline-lg-mobile": ["26px", { "lineHeight": "32px", "fontWeight": "700" }],
              "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "700" }]
          }
      }
  },
  plugins: [],
}
